//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.21 at 06:32:29 PM CET 
//


package io.spring.soap.getinfosongs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SongInfo" type="{http://spring.io/SOAP/GetInfoSongs}songTypeInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "songInfo"
})
@XmlRootElement(name = "getInfoSongResponse")
public class GetInfoSongResponse {

    @XmlElement(name = "SongInfo", required = true)
    protected ArrayList<SongTypeInfo> songInfo;

    /**
     * Gets the value of the songInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SongTypeInfo }
     *     
     */
    public ArrayList<SongTypeInfo> getSongInfo() {
        return songInfo;
    }

    /**
     * Sets the value of the songInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link SongTypeInfo }
     *     
     */
    public void setSongInfo(ArrayList<SongTypeInfo> value) {
        this.songInfo = value;
    }

}
