//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 11:22:06 AM CET 
//


package io.spring.soap.getalbums;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for album complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="album">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameAlbum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nameArtiste" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="annee" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "album", propOrder = {
    "nameAlbum",
    "nameArtiste",
    "annee"
})
public class Album {

    @XmlElement(required = true)
    protected String nameAlbum;
    @XmlElement(required = true)
    protected String nameArtiste;
    protected int annee;

    /**
     * Gets the value of the nameAlbum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameAlbum() {
        return nameAlbum;
    }

    /**
     * Sets the value of the nameAlbum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameAlbum(String value) {
        this.nameAlbum = value;
    }

    /**
     * Gets the value of the nameArtiste property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameArtiste() {
        return nameArtiste;
    }

    /**
     * Sets the value of the nameArtiste property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameArtiste(String value) {
        this.nameArtiste = value;
    }

    /**
     * Gets the value of the annee property.
     * 
     */
    public int getAnnee() {
        return annee;
    }

    /**
     * Sets the value of the annee property.
     * 
     */
    public void setAnnee(int value) {
        this.annee = value;
    }

}
