//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.21 at 06:32:29 PM CET 
//


package io.spring.soap.getalbums;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="album" type="{http://spring.io/SOAP/GetAlbums}album"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "album"
})
@XmlRootElement(name = "getAlbumResponse")
public class GetAlbumResponse {

    @XmlElement(required = true)
    protected ArrayList<Album> album;

    /**
     * Gets the value of the album property.
     * 
     * @return
     *     possible object is
     *     {@link Album }
     *     
     */
    public ArrayList<Album> getAlbum() {
        return album;
    }

    /**
     * Sets the value of the album property.
     *
     * @param value
     *     allowed object is
     *     {@link Album }
     *     
     */
    public void setAlbum(ArrayList<Album> value) {
        this.album = value;
    }

}
